POST http://localhost:3000/api/account HTTP/1.1
content-type: application/json

{
    "fsrAccount": 310034278401,
    "name": "ALLSTATE RETIREMENT SECLEND COLLAT",
    "currency": "USD",
    "walletAddress": "0xe7f1725e7734ce288f8367e1bb143e90bb3f0512"
}

###

POST http://localhost:3000/api/account HTTP/1.1
content-type: application/json

{
    "fsrAccount": 311345968400,
    "name": "GATX CORPORATION",
    "currency": "USD",
    "walletAddress": "0x5fbdb2315678afecb367f032d93f642f64180aa3"
}

###
POST http://localhost:3000/api/account HTTP/1.1
content-type: application/json

{
    "fsrAccount": 312969818400,
    "name": "TELEDYNE TECHNOLOGIES INCORPORATED",
    "currency": "USD",
    "walletAddress": "0x8626f6940E2eb28930eFb4CeF49B2d1F2C9C1199"
}

###

GET http://localhost:3000/api/account

###

GET http://localhost:3000/api/account/312969818400

###

PUT http://localhost:3000/api/account/312969818400 HTTP/1.1
content-type: application/json

{
    "name": "Different Name",
    "currency": "XXX",
    "walletAddress": "0xe7f1725e7734ce288f8367e1bb143e90bb3f0512"
}

###

PUT http://localhost:3000/api/account/312969818400 HTTP/1.1
content-type: application/json

{
    "name": "TELEDYNE TECHNOLOGIES INCORPORATED",
    "currency": "USD",
    "walletAddress": "0x8626f6940E2eb28930eFb4CeF49B2d1F2C9C1199"
}

###
DELETE http://localhost:3000/api/account/312969818400 HTTP/1.1

###
