POST http://localhost:3000/fund HTTP/1.1
content-type: application/json

{
    "CUSIP": "CUS912324A4",
    "description": "Short Term Treasuries",
    "deployAddress": "0xe7f1725e7734ce288f8367e1bb143e90bb3f0512"
}

###

POST http://localhost:3000/fund HTTP/1.1
content-type: application/json

{
    "CUSIP": "CUS111111A1",
    "description": "Short Term Treasuries",
    "deployAddress": "0xe7f1725e7734ce288f8367e1bb143e90bb3f0512"
}

###

POST http://localhost:3000/fund HTTP/1.1
content-type: application/json

{
    "CUSIP": "CUS222222A2",
    "description": "TBILLS",
    "deployAddress": "0xe7f1725e7734ce288f8367e1bb143e90bb3f0512"
}

###

GET http://localhost:3000/fund

###

GET http://localhost:3000/fund/CUS111111A1

###

PUT http://localhost:3000/fund/CUS912324A4 HTTP/1.1
content-type: application/json

{
    "description": "CORPORATES",
    "deployAddress": "0xda19b916df49add75e8b21939c83ccd094ff6cf9"
}

###

PUT http://localhost:3000/fund/CUS912324A4 HTTP/1.1
content-type: application/json

{
    "description": "MMF",
    "deployAddress": "0xbDA5747bFD65F08deb54cb465eB87D40e51B197E"
}

###
DELETE http://localhost:3000/fund/CUS111111A1 HTTP/1.1

